### ISSUE TITLE
Node.js engine requirement

### ISSUE THREAD

**Issue by abarani** [chrisguttandin/fast-unique-numbers#366]
I was wondering why this module specifically requires node `>=10.15.3` to be built:
https://github.com/chrisguttandin/fast-unique-numbers/blob/master/package.json#L62

I'm working on a project that requires `worker-timers` (that has a dependency on this module) but uses node 8 in the build pipeline and it is not easy upgradable to node 10.

Can the engine constraint be removed or reverted back to node 8?
I can open a PR if this is feasible.

**Comment by chrisguttandin** [comment]
Hi @abarani,

I understand that this is annoying but I hope it is only a theoretic issue. `worker-timers` does indeed depend indirectly on this module but it should not be execute on Node.js as it is only meant to run in the browser. Is the build process "only" complaining or does it throw an actual error?

I was probably too quick when I removed Node.js v8 support as soon as v10 became the latest stable version. Since Node.js v8 is about to be discontinued in less than two month I would rather not like to reenable it. But I will definitely keep supporting Node.js v10 until it gets discontinued this time and not jump to v12 directly.

**Comment by abarani** [comment]
Ah sorry, forgot to add that the issue is caused by yarn when adding the module:

```
# yarn add worker-timers@^5.0.34
yarn add v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error fast-unique-numbers@4.0.13: The engine "node" is incompatible with this module. Expected version ">=10.15.3". Got "8.16.2"
error Found incompatible module.
```

I don't think there will be any actual problem in the build process but I cannot verify as I cannot even install the module.

**Comment by chrisguttandin** [comment]
I think that yarn checks the engines property is generally a good thing. But here it is probably a false positive. You can disabled that check by using the [`--ignore-engines` flag](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines).

**Comment by abarani** [comment]
Good to know! I wasn't aware of the `--ignore-engines` option, this can be a temporary solution.

I still think though that removing the `engines` constraint from this module is a better solution. In the end, as you said, this is not going to be run on Node.js, as long as webpack or rollup are doing their jobs it shouldn't matter.

**Comment by chrisguttandin** [comment]
It's not running on Node.js when used as a dependency of `worker-timers` but it can be used on Node.js in other projects. The build contains a set of files specifically transpiled for Node.js. The configuration for that process can be found here: https://github.com/chrisguttandin/fast-unique-numbers/blob/master/config/babel/build.json. Since that config is only transpiling for Node.js v10 and above I set the engines property to signalize that.

**Comment by abarani** [comment]
Fair enough, thank you!
