### ISSUE TITLE
Engine breaks builds

### ISSUE THREAD

**Issue by AuspeXeu** [chrisguttandin/fast-unique-numbers#482]
https://github.com/chrisguttandin/fast-unique-numbers/commit/80255e1026c22cebaba7303e3f393d0f517d7d94

Is this commit really needed technically? It breaks a ton of builds on our side.

**Comment by rol-jacob** [comment]
Breaks our builds too, we are dependant on node <= 17.

**Comment by chrisguttandin** [comment]
Node.js v16 is no longer maintained and I don't test this package any longer on Node.js v16. That's why I updated the `engines` property. The change got published as a major version release. At least the packages that I maintain which depend on `fast-unique-numbers` and support Node.js should have had a major version bump, too.

Please let me know if you find out otherwise.

**Comment by rol-jacob** [comment]
@chrisguttandin, thanks for the quick answer! 
So worker-timers package uses latest minor of worker-timers-broker, (^7.x.x), so even if I downgrade worker-timers i still get 9.0.0 of unique-fast-numbers as a sub-dependency. 
I think it's this commit that should have been a major maybe.
 https://github.com/chrisguttandin/worker-timers-broker/commit/61267bd2bcbf1a3f7513c71b77c9da2a55bedd90
